 name: autoCommands
 version: 1.0
 description: Run commands automatically every x minutes!
 author: NXTGUY
 
 main: com.nxtcraft.Main
 database: false
 
 commands:
   autocommands:
     description: Base command for the autoCommand plugin.
     aliases: [autocommand, autocmd, acommand]